### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by vlalog** [Chimildic/goofy#1]
Я бы вынес доки (Readme.md) в отдельный сайт (chimildic.github.io/goofy).

Это не должно вызвать проблем, учитывая, что вся документация уже в `.md`. Нужно только выбрать шаблон, и разделить доки под него.

Однако, если Вам все же понадобится помощь, Вы можете связаться со мной здесь, или с помощью контактов, указанных на [vlalog.com](https://vlalog.com)

**Comment by Chimildic** [comment]
Создан отдельный [сайт](https://chimildic.github.io/goofy/#/)
