### ISSUE TITLE
Кэширование любимых треков

### ISSUE THREAD

**Issue by Chimildic** [Chimildic/goofy#153]
### Описание
Создать механизм накопления любимых треков на Google Диске

### Цель
- [x] Уменьшить количество затрачиваемых запросов
- [x] Ускорить время выполнения (при большом количестве треков)

### Ограничение
- [x] Сохранить расположение и внешнее поведение `Source.getSavedTracks`
- [x] Не создавать новую публичную функцию для чтения файла
- [x] Не занимать новый триггер

### Заметки
- Как часто обновлять файл из под триггера? (Раз в сутки)
- Как совместить актуальность списка и не увеличить время выполнения из-за работы с `Cache`? (Тесты с `console.time`)
- Попробовать выделить управляющий модуль, который будет читать и обновлять кэш по запросу за счет передачи способа получения новых элементов.

**Comment by Bedmit** [comment]
> * Как часто обновлять файл из под триггера? (Раз в сутки)

Уже пару месяцев использую запись любимых треков в кэш. И по опыту использования Spotiboi. Записи раз в сутки более чем достаточно. Вопрос только в возможности выбора времени этой записи. 

Второй вопрос, каюсь не понял.

**Comment by Chimildic** [comment]
@Bedmit для чего нужен выбор времени при единичном обновлении?

Вопросы больше для себя оставил, чтобы было к чему возвращаться

**Comment by Bedmit** [comment]
> для чего нужен выбор времени

Для формирования плейлистов генирирующихся раз в сутки, очень желательно чтобы информация в нем была актуальная. Особенно в части любимых треков. Логично что лучше всего такие плейлисты формировать ночью, когда уже не слушаешь музыку, а информация по лайкам наиболее полная. Т.е. как раз после записи их в кэш. 
Но у всех это время может быть разным. В том числе и из-за часовых поясов. 

Кончено если это не сопряжено с какими-либо сложностями. Я думал это всего лишь определение времени триггера.

**Comment by Bedmit** [comment]
По ходу написания ответа возник вопрос. Если это будет использовано внутри `Source.getSavedTracks` то лайки добавленные в течении текущих суток в этот файл добавятся только ночью. Получается что  скрипты использующие их в течении дня, работать не будут?
Тогда может нужна будет функция дающая возможность моментально получить сегодняшние лайки?

**Comment by Chimildic** [comment]
> это всего лишь определение времени триггера

@Bedmit не хочется занимать новый триггер. Триггер истории обычно до 30 секунд работает. Остается много времени до лимита. Можно выполнить и другие задачи. Только встает необходимость изобрести велосипед, который будет ехать только в назначенное время, а не каждые 15 минут. 

Конечно можно пустить одновременно. Но лайки обновляются значительно реже истории. Пусть даже по одному запросу, но в пустую будет работать большую часть времени.

> моментально получить сегодняшние лайки

Как представил, проблемы с новыми лайками за день не будет. Потому что функция все же будет делать запросы в некоторых случаях. Ближе к реализации подумаю над деталями. 

Остается проблема вычисления наоборот удаленных лайков. На первый взгляд, без запроса всех сразу - их не вычислить. С другой стороны, удаление лайка еще более редкое событие и раза в сути или даже реже будет достаточно для полного обновления кэша.

**Comment by Bedmit** [comment]
Блин, прочитал, а ответить забыл )

> Остается проблема вычисления наоборот удаленных лайков.
Мне кажется это вообще не проблема, чтобы ее хоть как-то учитывать. Я очень активно в течении дня лайкаю/разлайкиваю, но при этом не могу представить сценарий при котором мне бы в течении дня потребовалась информация о треках с которых я снял лайк. По логике этот трек нужен не для использования, а только для исключения из предлагаемых. А это в данном случае уже будет делать история прослушивания. Актуализации лайков раз в сутки хватает с головой.

**Comment by Chimildic** [comment]
Пока не удается придумать устойчивый вариант с заданными ограничениями. 
Все таки сложно изменять код, на котором уже многое написано.

**Comment by Bedmit** [comment]
Может тогда оставить эту идею?
Те кому нужна в этом вопросе оптимизация и так могут сами записывать лайки в кэш, и пользовался этим файлом. А те у кого их мало, эта оптимизация и не особо затронет. Страшнее получить какие-то ошибки. Или переделывать что-то в старых, уже работающих скриптах.

**Comment by Chimildic** [comment]
Не стал трогать `Source.getSavedTracks`. Сделал клерка, который по заданному времени выполнит кэширование в рамках 15 минутного триггера: раз в сутки добавляет новые лайки и раз в неделю обновляет целиком (чтобы актуализировать кэш на случай удаления лайков). Для получения обычный `Cache.read` с именем файла.

Часовой пояс можно настроить в манифесте проекта. Напишу отдельно.
Вроде работает, послежу у себя пока.

**Comment by Chimildic** [comment]
@amd64fox нет. Закомментируйте строчки в `runTasks_`.
```js
RecentTracks.update();
// let isUpdatedSavedTracks = Clerk.runOnceAWeek('monday', '01:00', updateSavedTracks);
// !isUpdatedSavedTracks && Clerk.runOnceAfter('01:00', appendSavedTracks);
```
