### ISSUE TITLE
Ошибка Filter.rangeTracks

### ISSUE THREAD

**Issue by Bondian** [Chimildic/goofy#179]
Ещё одна ошибка с фильтром Filter.rangeTracks (без фильтра функция работает).
Файл прилагаю:
[rus.zip](https://github.com/Chimildic/goofy/files/8488066/rus.zip)

````  
  let tracks = Cache.read('rus.json');

  Filter.rangeTracks(tracks, {
    album: {
      release_date: { startDate: new Date('2022.01.01'), endDate: new Date('2022.12.31') },
    }
  });

  Playlist.saveWithReplace({
    name: 'testt',
    public: false,
    tracks: Selector.sliceRandom(tracks, 10),
  });

 Лог:
14:03:19	Примечание	Выполнение начато
14:03:32	Информация	Операция продолжится после паузы 2с.
14:03:39	Информация	Операция продолжится после паузы 4с.
14:03:50	Информация	Операция продолжится после паузы 11с.
14:04:18	Информация	Операция продолжится после паузы 14с.
14:04:50	Информация	Операция продолжится после паузы 13с.
14:05:12	Ошибка	
TypeError: Cannot read property 'id' of null
(функция без названия)	@ library.gs:2878
cacheToFullObj	@ library.gs:2878
cache	@ library.gs:2836
getCache	@ library.gs:2827
rangeTracks	@ library.gs:1003
myTestFunction	@ Без названия.gs:5

_Originally posted by @Bondian in https://github.com/Chimildic/goofy/discussions/168#discussioncomment-2565624_

**Comment by Chimildic** [comment]
Ошибка не воспроизводится. Попробуйте обновить свой код библиотеки.

**Comment by Bondian** [comment]
Да, действительно, обновлённый код помог. Спасибо.
Когда возникают ошибки - в первую очередь захожу сюда: https://chimildic.github.io/goofy/#/changelog . Но там висит верхняя версия 1.7.0 как и у меня. Трудно догадаться, что есть более свежая версия и нужно ещё жмакнуть по ссылке [Скопируйте обновленный код](https://script.google.com/d/1DnC4H7yjqPV2unMZ_nmB-1bDSJT9wQUJ7Wq-ijF4Nc7Fl3qnbT0FkPSr/edit?usp=sharing) чтобы её обнаружить...
