### ISSUE TITLE
Изменение порядка локальных файлов в плейлисте

### ISSUE THREAD

**Issue by AndBoyS** [Chimildic/goofy#240]
Порядок локальных файлов можно менять в плейлисте при помощи Spotify API. Можно ли это сделать через Goofy? В идеале получить список всех треков в плейлисте, включая локальные, поменять порядок, и сохранить. Логично было бы использовать для этого Playlist.saveWithUpdate, но как получить список локальных файлов через Goofy мне непонятно

**Comment by Chimildic** [comment]
goofy игнорирует локальные файлы потому что их нельзя добавить в плейлист через API. 
Переупорядочивание "на живую" также не поддерживается из-за лимита на запросы от Apps Script. 

У `saveWithUpdate` специфика сохранить дату добавления всех треков (добавление в начало или конец, точечное удаление). Глобальная сортировка массива из кода игнорируется. `saveWithReplace` удаляет все треки и добавляет заново - поэтому вся сортировка меняется.
