### ISSUE TITLE
Troubleshooting help - Error 500

### ISSUE THREAD

**Issue by ladywhiskers** [Chimildic/goofy#247]
Every script I run for the last few weeks (possibly longer) gives the following error:

`	Number: 500
Address: https://api.spotify.com/v1/me/tracks?offset=8000&limit=50&locale=AU
Response text: {
  "error" : {
    "status" : 500,
    "message" : "Server error."
  }
} 

Description and resolution of errors: https://chimildic.github.io/goofy/#/errors`

The `offset` number changes after every attempt, my preliminaey investigating leads me to believe that this is an issue with my user token.

![image](https://github.com/Chimildic/goofy/assets/99696830/fe07d9fc-6153-492d-ae1f-b364a74edc9e)

I'm not sure what steps to take to resolve this issue, could someone please point me in the right direction?

**Comment by Chimildic** [comment]
The errors with 500+ code are not our issue. It is problem on Spotify server side. Usually such errors far away very fast.

Try to create new app in Spotify Dashboard in order to set new client id and client secret in goofy's config file and auth with them.
