### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by costaline** [Chimildic/Goofy#3]
Возникает при попытке получить треки из плейлиста, найденного только по имени
```
TypeError: Cannot read property 'length' of undefined
    at [unknown function](Library:887:23)
    at push(Library:886:25)
    at [unknown function](Library:320:29)
    at getTrackItems(Library:313:30)
    at getTracks(Library:309:30)
    at getTracksByPlaylistName(actions:2:25)
```

В объекте с данными по плейлисту, **tracks** не содержит свойства **items**, которое требуется в **Source.getItemsByPlaylistObject()**
![изображение](https://user-images.githubusercontent.com/46042197/101046355-2d435800-35ab-11eb-8258-2131fb811f3a.png)

**Comment by Chimildic** [comment]
Попробуйте обновить библиотеку сейчас и напишите исправлена ли ошибка.

**Comment by costaline** [comment]
Теперь ок. Спасибо
